### ISSUE TITLE
Function body and signature on same level

### ISSUE THREAD

**Issue by GenesisTMS** [UserNobody14/tree-sitter-dart#12]
Would it make more sense to have tree like this? As `function_body` will never exists without `method_signature` or `function_signature`.

```
function_signature [43, 0] - [43, 8]
  void_type [43, 0] - [43, 4]
  name: identifier [43, 5] - [43, 6]
  formal_parameter_list [43, 6] - [43, 8]
function_body [43, 8] - [45, 1]
  block [43, 8] - [45, 1]
```
this:
```
function_signature [43, 0] - [43, 8]
  void_type [43, 0] - [43, 4]
  name: identifier [43, 5] - [43, 6]
  formal_parameter_list [43, 6] - [43, 8]
  body: function_body [43, 8] - [45, 1]
    block [43, 8] - [45, 1]
```

It is really just suggestion. I am very new to _tree-sitter-or-language-spec-stuff_.
Thanks

**Comment by UserNobody14** [comment]
Sorry to respond so late, I haven't been logging into my github as often due to work and personal issues. As far as why things are the way they are (and I agree it's a bit of a strange organization) the reason is that the grammar was (originally) written to conform to the dart grammar reference [here](https://spec.dart.dev/DartLangSpecDraft.pdf). As far as your specific item goes, I think they are separated in the grammar reference because in dart classes one can write a function without a body, as a kind of abstract function:
```

class Calculate_Total { 
   int ret_tot() {} 
}  
class Calculate_Discount { 
   int ret_dis() {} 
}
class Calculator  implements Calculate_Total,Calculate_Discount { 
   int ret_tot() { 
      return 1000; 
   } 
   int ret_dis() { 
      return 50; 
   } 
}```

so that would be why function signatures must be separated (I think, the project has been proceeding steadily without me for a while).

**Comment by GenesisTMS** [comment]
Ah! Got it. Thanks for explanation :)
